### ISSUE TITLE
Is there a way to use unity-license instead of unity-serial?

### ISSUE THREAD

**Issue by Zen12** [yukiarrr/unity-build-action#11]
unity-serial is used for purchased versions, is there a way to use free version in order to activate unity?

**Comment by yukiarrr** [comment]
@Zen12 Thanks for creating the issue!
With free version, you can get a serial code in the following ways.
https://www.yukiarrr.com/entry/2020/04/19/224851

The article is written in Japanese, did you get a serial code?

**Comment by Zen12** [comment]
Yes, thanks!
